config/routes.rb
Rails.application.routes.draw do
  resources :videos, only: [:new, :index]
  root to: 'videos#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#fail'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
  end
 
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YtUploder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse">
	    <div class="container">
	      <div class="navbar-header">
	        <%= link_to 'YT Uploader', root_path, class: 'navbar-brand' %>
	      </div>
	      <ul class="nav navbar-nav">
	        <li><%= link_to 'Videos', root_path %></li>
	        <li><%= link_to 'Add Video', new_video_path %></li>
	      </ul>
	    </div>
	</div>
	<div class="container">
	    <% flash.each do |key, value| %>
	      <div class="alert alert-<%= key %>">
	        <%= value %>
	      </div>
	    <% end %>
	 
	    <%= yield %>
	</div>
</body>
</html>

app/views/videos/index.html.erb
<div class="jumbotron">
  <h1>YouTube Uploader</h1>
  <p>Upload your video to YouTube and share it with the world!</p>
  <p><%= link_to 'Upload video now!', new_video_path, class: 'btn btn-primary btn-lg' %></p>
</div>

app/views/videos/new.html.erb
<div class="page-header">
  <h1>Upload Video</h1>
</div>